### ISSUE TITLE
Add a Sponsor/Supporter section in landing page

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#10]
The section will include the following:

- [x] A link asking people to contact if they are interested to support us. Something like: "Are you interested to support PyCon India 2020? Please reach out to us at <email id>
- [x] design a grid of supporters (logo) with varying size depending on their support.

**Comment by SiddharthSimharaju** [comment]
A first draft of the sponsor's section: https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=234%3A0

**Comment by SaptakS** [comment]
@SiddharthSimharaju Looks great!

**Comment by SaptakS** [comment]
@ajaynair710 please take a look into the implementation of this issue.
