### ISSUE TITLE
'Add to Calendar' link under the talks

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [pythonindia/inpycon2020#108]
**Proposal:**
In the [schedule](https://in.pycon.org/2020/#schedule) section, all the talks can have a `Add to Calendar` link under their title and speaker name.
It could just let users download a `.ics` file with the details of the talk and they can add it to their preferred calendar application.

**Comment by palnabarun** [comment]
Hi @Vibhu-Agarwal :wave:, we have been already thinking about this. Thanks for putching in too. :slightly_smiling_face:

**Comment by vipulgupta2048** [comment]
Resolved with #109
