### ISSUE TITLE
Add design and content for about section

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#11]
We need more content in the about section:

- [x] A little about PyCon India
- [x] How PyCon India is different this year? (Online, different new things, improvements?)
- [x] A link to CFP to be phrased in the content. Something like: "Willing to talk in our event? Our CFPs are already open!"

**Comment by vipulgupta2048** [comment]
@Sc0rpi0n101 and Rithin Can you take the lead on this. Please ping on Zulip if you have any questions. This would be a great starting task for you all to learn more about the conference.

**Comment by Sc0rpi0n101** [comment]
Sure

Where can I find some info about PyCon to get started?

**Comment by rithin-jose** [comment]
hi this is rithin, @Sc0rpi0n101 I think we can get all the necessary details from https://in.pycon.org/2019/

**Comment by rithin-jose** [comment]
[this](https://docs.google.com/document/d/1gENmG53uAYLi05lhK5lSge0HT2ciCggA7Z9UOFAG14g/edit?usp=sharing) basically sums up what I have done. A few contents about how the virtual conclave is diffrent can be added since i wasn't sure so didn't add it.

**Comment by Sc0rpi0n101** [comment]
the about section looks good. Although we should add we'll be going online this year instead of Bangalore.
IMO the FAQs should have their own page instead of being on the about page. 

I have some suggesstions for the content for the about section. I'll link it here by morning.

**Comment by vipulgupta2048** [comment]
@rithin-jose @Sc0rpi0n101 Added my suggestions, please review. 
Also, please read https://in.pycon.org/blog/2020/2020-call-for-proposals-announcement.html for more context on tone needed for this PyCon India

**Comment by Sc0rpi0n101** [comment]
@vipulgupta2048 @rithin-jose I've drafted a little something for the About page [here](https://docs.google.com/document/d/1_JqWQJQrnOhFbRy0ha6JxvjuFlhwZld6nLn8DDWTHCE/edit?usp=sharing). 

There's still a lot of room for improvement. So, feedback please.

**Comment by SaptakS** [comment]
> [this](https://docs.google.com/document/d/1gENmG53uAYLi05lhK5lSge0HT2ciCggA7Z9UOFAG14g/edit?usp=sharing) basically sums up what I have done. A few contents about how the virtual conclave is diffrent can be added since i wasn't sure so didn't add it.

I am thinking of adding the short concise version of this in the landing page.

> @vipulgupta2048 @rithin-jose I've drafted a little something for the About page [here](https://docs.google.com/document/d/1_JqWQJQrnOhFbRy0ha6JxvjuFlhwZld6nLn8DDWTHCE/edit?usp=sharing).

...and then make an entire separate About Page for adding the more detailed version by @Sc0rpi0n101

**Comment by vipulgupta2048** [comment]
Thanks @SaptakS let us know if you like any more changes to be done.

**Comment by ananyo2012** [comment]
@SaptakS Based on your previous content for now we just need to update the content in the homepage.

**Comment by ananyo2012** [comment]
@vipulgupta2048 Do you want to take up this issue to create a separate about page ?

**Comment by vipulgupta2048** [comment]
Yes, let's do it. 
@Sc0rpi0n101 Want to take the lead on that. It's your content.

**Comment by Sc0rpi0n101** [comment]
> 
> 
> Yes, let's do it.
> @Sc0rpi0n101 Want to take the lead on that. It's your content.

Sure, do we have a wiki page or some contributor docs about adding a page and stuff?

**Comment by vipulgupta2048** [comment]
Not sure, but @ananyo2012 can add you the workgroup. Thanks!

**Comment by ananyo2012** [comment]
@Sc0rpi0n101 Any update on this ?

**Comment by Sc0rpi0n101** [comment]
I can have a PR tomorrow.

Btw, how would you like the navigation to work?
Currently, the about button redirects to the summary on the home page. Would you like if the button now redirects to the About page and the summary is just there on the home page, or should I add a `Know More` button or something like that to the about section which will then redirect to the new page?

**Comment by ananyo2012** [comment]
Yes the "Know More" link should be good.

**Comment by anistark** [comment]
This can be closed. Right?

 @ananyo2012 @SaptakS
