### ISSUE TITLE
Add CFP section

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#12]
We need a CFP section.

Deliverables:

- [x] A separate section mentioning an excerpt about different things people can talk about.
- [x] A scope for mentioning end date of CFP (before end date is fixed, we will keep it as "Submit Soon!!" or similar)
- [x] A big button linking to CFP

**Comment by ananyo2012** [comment]
Isn't the Editorial there at junction already ?

**Comment by SaptakS** [comment]
Taking an excerpt from the [About Page content](https://github.com/pythonindia/inpycon2020/issues/11#issuecomment-640060890) I am thinking of going with the following content:

>
> ## Want to submit a talk/workshop for the conference?
>
> Technical talks are an important part of PyCon India, the core of the conference essentially. Talks are selected through a CFP (Call For Proposals) process where interested speakers propose their talks and an editorial panel designated by the organisers makes the selections. 
>
> With PyCon India 2020 being online this year, we are introducing preview videos to our proposal submission workflow. Preview videos are you talking about your proposal, topics you intend to cover in the talk, and how you intend to cover them. It will be immensely helpful for reviewers to go through preview videos and take that into account before making final decisions on your talk proposal. 
>
> You can check out our [CFP page](https://in.pycon.org/cfp/2020/proposals/) and [our blog](https://in.pycon.org/blog/2020/2020-call-for-proposals-announcement.html) for more details.
>
> "Submit a Talk" button

Feel free to add infographics if you feel is needed associated to each paragraph

**Comment by SaptakS** [comment]
@siddharthsimharaju can you have a look into this?

**Comment by SiddharthSimharaju** [comment]
Working on it. Will keep you updated.

**Comment by SiddharthSimharaju** [comment]
Design for the CFP section.
https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=241%3A0

**Comment by SaptakS** [comment]
Looks good. I would say just drop the Topic of Interest section. That discourages some good talks which might not fall under any of that topic to submit.

Also, it would be great if you can add two informations somewhere in the design:
1. Designated editorial panel makes the selections
2. Preview videos about the proposal and topics intended to be covered.

Also change "Send Proposal" to "Submit Proposal"

**Comment by SiddharthSimharaju** [comment]
https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=241%3A0

**Comment by ananyo2012** [comment]
This is all done :tada:
