### ISSUE TITLE
Add a button for CFP in banner section

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#13]
For the time, replace the "Get Passes" button to "Submit Proposal in banner section.

**Comment by agarwalrounak** [comment]
Hi @SaptakS, I can't find a "Get Passes" button. Has it already been replaced?

**Comment by SaptakS** [comment]
@agarwalrounak all the issues are based on the dev branch and not the currently deployed website.

**Comment by agarwalrounak** [comment]
Got it, thank you! Will send a PR soon.

**Comment by SaptakS** [comment]
Fixed in #16
