### ISSUE TITLE
Create a page layout for different pages

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#14]
Create a simple page layout with navigation and fonts matching the current design. This layout is to be used for different pages like:

- Code of Conduct
- Privacy policies
- Any other terms and conditions.

Check https://jekyllrb.com/docs/layouts/ to know more about how to create layouts

**Comment by Sangarshanan** [comment]
would be happy to help out here :raised_back_of_hand:

**Comment by SaptakS** [comment]
@Sangarshanan sure! Looking forward to a PR
