### ISSUE TITLE
Update sponsorship text

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#18]
How does this sound 

For support reach out to support@pycon.in

_Originally posted by @satyaakam in https://github.com/pythonindia/inpycon2020/pull/17_

**Comment by SaptakS** [comment]
> PyCon India is volunteer driven event. Sponsoring the event helps to sustain and grow
> the conference and the community. Sponsors help in making the conference affordable,
> and maintain the inventory for the conference.

_Originally posted by @satyaakam in https://github.com/pythonindia/inpycon2020/pull/17_

**Comment by Sc0rpi0n101** [comment]
How about this?

PyCon India is a volunteer-driven event. Sponsoring the event helps bring the volunteers effort to fruition,  sustain, and improve the conference and grow the community. Sponsors help us make the conference affordable, bring more facilities to our attendees, and maintain the inventory for the conference.

**Comment by ananyo2012** [comment]
@Sc0rpi0n101 Can you send a PR for this ?

**Comment by Sc0rpi0n101** [comment]
Sure
