### ISSUE TITLE
Update CFP content in landing page

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#20]
You always wanted to speak in public or  wanted to inspire the next generation of audience here is an opportunity for you , we have been accommodating every level of talks more so ever beginners is encourages to submit one. This year being a virtual conference it gives us a  unique opportunity to practice and share your videos for the CFP

_Originally posted by @satyaakam in https://github.com/pythonindia/inpycon2020/pull/17_

**Comment by Sc0rpi0n101** [comment]
How does this look?

Have you ever wanted to speak in public, share your experiences and expertise with others? 

We have an opportunity for you to share what you have learned with others and inspire the next generation of audiences. Our community loves to learn, and we welcome every level of talk. Everyone is a beginner at something at some point, and we love beginner talks. So, we encourage you to submit a proposal if you have anything to share, no matter the difficulty level. The virtual nature of the conference this year gives us a unique opportunity for you to share a video for your talk and practice with us.

**Comment by vipulgupta2048** [comment]
Thanks, @Sc0rpi0n101 I feel we are repeating love a few time so can replace it with other synonyms

We have a unique opportunity for you to share what you have learned with others and inspire the next generation of audiences. Our community is forever inclined to learn, grow, and expand their knowledge. Hence, it welcomes talks of every level. Whether you are a beginner filling the proposal for your first talk or have been giving talks for the past 10+ years. We encourage you all to draft a proposal, no matter the difficulty level. The virtual nature of this annual conference this year gives a unique chance for you to share your insights & learnings to the world right from the comforts of your home. 

Can be trimmed as required, what say @SaptakS @satyaakam

**Comment by KanakKvdi** [comment]
**Here's mine:**

We know you've always wanted to speak out in public, share your experiences, your expertise with others. But there was always one thing missing - an appropriate Platform!

Now, look no further! PyCon India 2020 is the platform you've always wanted! We bring you an amazing opportunity to share with others what you have learned and acquired and inspire the next generation of audiences. Our community is passionate about learning, and we gladly welcome every level of talk. Everyone is a beginner at something. And we LOVE beginner talks! We're sure PyCon India 2020 will take you up a notch from where you are now!
We, therefore, encourage you to submit a proposal if you think you have something worthwhile to share, no matter the difficulty level. The virtual nature of the conference this year gives us a unique opportunity to enable it for you to share a video of your talk and practice with us. Voila!

**Comment by ananyo2012** [comment]
Updated with @vipulgupta2048 's content. Marking this closed
