### ISSUE TITLE
Refresh favicon

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/inpycon2020#24]
The [favicon](https://github.com/pythonindia/inpycon2020/blob/master/favicon.png) in the repository is of the interim PyCon India 2020 logo. The logo should be refreshed with the new design.

**Comment by ananyo2012** [comment]
Started discussion for this in design group

**Comment by ananyo2012** [comment]
Favicon is uploaded to https://drive.google.com/drive/folders/1FGisVxBKXdPiGVOkkHA6r71Q2VBuR-us?usp=sharing

**Comment by singh-sarabjeet** [comment]
Correct me if I'm wrong, this issue only pertains to replacing the favicon with [new logo](https://drive.google.com/file/d/1XgkY5hhXxeuhan72-eHbCm4KoXn750fI/view?usp=sharing).
If other icons need to be changed, please give a detailed description.
