### ISSUE TITLE
Enable caching for static assets 

### ISSUE THREAD

**Issue by bhansa** [pythonindia/inpycon2020#28]
We should add a service worker to do caching of static resources like js, css, images etc. which will result in faster page load for returning users.
Let me know if this is a good idea, I will be able to help on this.

**Comment by ananyo2012** [comment]
@bhansa This sounds sounds good. We also need to enable hashing on the assets to update the cache when the assets update. Please send a PR addressing both issues

**Comment by ananyo2012** [comment]
@bhansa Do you want to work on this ?

**Comment by bhansa** [comment]
Yes, ananyo. Will send a PR.
