### ISSUE TITLE
Add Social Media Icons + Zulip in the footer

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2020#33]
Opening an issue to track this, as we don't have logos for Linkedin, Mailing list and Zulip.

**Comment by ananyo2012** [comment]
Started discussion for this with design team.

**Comment by ananyo2012** [comment]
Assets are uploaded at https://drive.google.com/drive/folders/1FGisVxBKXdPiGVOkkHA6r71Q2VBuR-us?usp=sharing

Please add the LinkedIn, Email and Chat icons with the appropriate links in footer.

LinkedIn -> https://www.linkedin.com/company/pyconindia/
Email -> https://mail.python.org/mailman/listinfo/inpycon
Chat -> https://pyconindia.zulipchat.com/

**Comment by vipulgupta2048** [comment]
Thanks @ananyo2012 I will open a PR regarding the same.
