### ISSUE TITLE
Adding setup and contribution guidelines in Readme

### ISSUE THREAD

**Issue by Sc0rpi0n101** [pythonindia/inpycon2020#36]
We should add some instructions about setting up the blog like how to install Jekyll, and the dependencies, and setting up a local server or at least give the appropriate reference links, where applicable, in the README. 

It might also be a good idea to add some basic instructions and information about adding pages, editing current pages, and sections, etc. as Contribution guidelines for new contributors.

**Comment by ananyo2012** [comment]
@Sc0rpi0n101 Can you add a CONTRIBUTING.md and link it to the readme ?

**Comment by Sc0rpi0n101** [comment]
Sure
