### ISSUE TITLE
Navbar not visible in home page

### ISSUE THREAD

**Issue by AkashM398** [pythonindia/inpycon2020#40]
The navbar is not shown at the homepage but it is been shown from the about page, it is recommended to fix it.
I have attached the screenshot below

![https://in.pycon.org/2020/](https://user-images.githubusercontent.com/38563661/86955592-72d33480-c175-11ea-8e2f-f78db6e70e0a.png)

**Comment by ananyo2012** [comment]
This is not a bug but the design of the website
