### ISSUE TITLE
Add Ticket Section

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2020#46]
Follow the design in https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=439%3A1 to add the ticket section to the website

**Comment by CodesbyUnnati** [comment]
We have to make the full page given on the figma design or we just have to make the ticket section?

**Comment by CodesbyUnnati** [comment]
Tried Desktop view ->https://codepen.io/unnatimishra/pen/MWKMqLO
Please review it.
![tickets](https://user-images.githubusercontent.com/54355445/88951102-2df17800-d2b3-11ea-8417-b5c6a3c16729.PNG)

**Comment by Sc0rpi0n101** [comment]
How about having the ticket name a different color than the description?

**Comment by PawanKolhe** [comment]
I'd love to work on this in the coming weekend.

**Comment by palnabarun** [comment]
This is good to be closed.
