### ISSUE TITLE
Add OpenGraph Tags to website for better SEO

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2020#47]
We can add OpenGraph tags to the website for better SEO and search engine results. Tags recommended, 
- `og:title`
- `og:image`
- `og:description`

and more as per discretion. 
@Pradhvan can come up with a simple 1200x630 px banner with PyCon India logo and dates below it. 
Tagging @ananyo2012 for review.

**Comment by palnabarun** [comment]
@vipulgupta2048 -- Since this is done, can we close the issue?

**Comment by vipulgupta2048** [comment]
@palnabarun Is it done? The pull request I have opened was for the blog. 
Also, https://www.opengraph.xyz/ still shows a blank on tags.

**Comment by palnabarun** [comment]
Ummm, yes. You're right. Are we blocked on anything here?

**Comment by vipulgupta2048** [comment]
@palnabarun Not that I know off, it seems like no one took it up. 
I created a OG image for the blog which can be grabbed from here ... damn can we at least merge this https://github.com/pythonindia/inpycon-blog/pull/315

**Comment by vipulgupta2048** [comment]
@palnabarun When that is merged, then one can copy the snippet below. Fill it with information and drop it in the website code at the right place with the `og:image` 

```

        <title>PyCon India - Home</title>
        <meta name="description" content="">

        <!-- Facebook Meta Tags -->
        <meta property="og:url" content="https://in.pycon.org/2020">
        <meta property="og:type" content="website">
        <meta property="og:title" content="PyCon India - Home">
        <meta property="og:description" content="">
        <meta property="og:image" content="">

        <!-- Twitter Meta Tags -->
        <meta property="twitter:url" content="https://in.pycon.org/2020">
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:title" content="PyCon India - Home">
        <meta name="twitter:description" content="">
        <meta name="twitter:image" content="">
```

**Comment by bhansa** [comment]
Hi, I would like to work on this issue. Let me know the next steps.
