### ISSUE TITLE
Add an outreach partners section

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2020#53]
This section will contain logos of our outreach partners.

Please put this on priority. Need it by this weekend.

A clean design like this below should be fine:

![Sample Outreach Partners](https://mobirise.com/extensions/businessm4/assets/images/clients-676x451.jpg)

Of course this is just a sample.

**Comment by palnabarun** [comment]
Do we need this anymore since we are not looking at Outreach Partners anymore?

**Comment by anistark** [comment]
The PR is still open and we got a few, like 4 to be exact. So, not sure what to do at this point.
