### ISSUE TITLE
Create the Sponsorship page and go live with announcements  

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020#66]
The sponsorship prospectus is live here: https://in.pycon.org/2020/sponsorship-prospectus.pdf
We have a section in the same PyCon India 2020 page to highlight this doc. We might use the previous year 
https://in.pycon.org/2019/#sponsorship contents for website.

Apart from that we need following things to go live with announcements:

- [ ] Blog content for Sponsorship

- [ ] Email contents for announcements to different mailing list

- [ ] Social Media buzz

We will try to go live by end of today.

**Comment by sayanchowdhury** [comment]
Closing this issue in favor of pythonindia/inpycon2020-tasks#68
